// System icons from Bootstrap
// https://icon-sets.iconify.design/bi/

export * as rotate from '@iconify/icons-bi/arrow-clockwise';
export * as bell from '@iconify/icons-bi/bell';
export * as bellFill from '@iconify/icons-bi/bell-fill';
export * as checkCircle from '@iconify/icons-bi/check-circle';
export * as checkFill from '@iconify/icons-bi/check-circle-fill';
export * as check from '@iconify/icons-bi/check-lg';
export * as clock from '@iconify/icons-bi/clock';
export * as cloudDownload from '@iconify/icons-bi/cloud-arrow-down';
export * as cloudUpload from '@iconify/icons-bi/cloud-arrow-up';
export * as download from '@iconify/icons-bi/download';
export * as envelope from '@iconify/icons-bi/envelope';
export * as envelopeFill from '@iconify/icons-bi/envelope-fill';
export * as exclamationCircle from '@iconify/icons-bi/exclamation-circle';
export * as exclamationFill from '@iconify/icons-bi/exclamation-circle-fill';
export * as exclamation from '@iconify/icons-bi/exclamation-lg';
export * as eye from '@iconify/icons-bi/eye';
export * as eyeSlash from '@iconify/icons-bi/eye-slash';
export * as thumbs from '@iconify/icons-bi/hand-thumbs-up';
export * as infoCircle from '@iconify/icons-bi/info-circle';
export * as infoFill from '@iconify/icons-bi/info-circle-fill';
export * as info from '@iconify/icons-bi/info-lg';
export * as questionCircle from '@iconify/icons-bi/question-circle';
export * as questionFill from '@iconify/icons-bi/question-circle-fill';
export * as question from '@iconify/icons-bi/question-lg';
export * as search from '@iconify/icons-bi/search';
export * as ban from '@iconify/icons-bi/slash-circle';
export * as sortAlphaDown from '@iconify/icons-bi/sort-alpha-down';
export * as sortAlphaUp from '@iconify/icons-bi/sort-alpha-up-alt';
export * as sortDown from '@iconify/icons-bi/sort-down';
export * as sortUp from '@iconify/icons-bi/sort-up';
export * as upload from '@iconify/icons-bi/upload';

// TODO: These don't match well
export * as graphBar from '@iconify/icons-bi/bar-chart';
export * as dash from '@iconify/icons-bi/dash';
export * as lock from '@iconify/icons-bi/lock';
export * as lockFill from '@iconify/icons-bi/lock-fill';
export * as user from '@iconify/icons-bi/person';
export * as userCircle from '@iconify/icons-bi/person-circle';
export * as graphPie from '@iconify/icons-bi/pie-chart';
export * as circle from '@iconify/icons-bi/record';
export * as circleFill from '@iconify/icons-bi/record-fill';
export * as share from '@iconify/icons-bi/share';
export * as phone from '@iconify/icons-bi/telephone';
export * as xmarkCircle from '@iconify/icons-bi/x-circle';
export * as xmarkFill from '@iconify/icons-bi/x-circle-fill';
export * as xmark from '@iconify/icons-bi/x-lg';
